movies-master/config/routes.rb
Movies::Application.routes.draw do
  resources :libros

  get '/movies' => 'movies#index'
  get '/movies/new' => 'movies#new'
  get '/movies/:id' => 'movies#edit'
  post '/movies' => 'movies#create'
  post '/movies/:id' => 'movies#update'
  root 'movies#index'

  

end

movies-master/app/models/libro.rb
class Libro < ActiveRecord::Base
end

movies-master/app/models/movie.rb
class Movie < ActiveRecord::Base

	validates :name , :presence => true


end

movies-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

movies-master/app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render action: 'show', status: :created, location: @libro }
      else
        format.html { render action: 'new' }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:name)
    end
end

movies-master/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	skip_before_filter :verify_authenticity_token 
	def index


		@movies = Movie.all
	end

	def new
		@movie = Movie.new

	end

	def edit
		@movie = Movie.find(params[:id])

	end

	def update
		@movie = Movie.find(params[:id])
		@movie.name = params[:movie][:name]

		if @movie.save 
			redirect_to '/', notice: 'La pelicula ha sido actualizada exitosamente'
		else
			render 'edit'
		end	

	end


	def create
		@movie = Movie.new
		@movie.name = params[:movie][:name]


		if @movie.save 
			redirect_to '/', notice: 'La pelicula ha sido creada exitosamente'
		else
			render 'new'
		end
		
	end



end

movies-master/app/helpers/application_helper.rb
module ApplicationHelper
end

movies-master/app/helpers/libros_helper.rb
module LibrosHelper
end

movies-master/app/helpers/movies_helper.rb
module MoviesHelper
end

movies-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hola</title>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

movies-master/app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

movies-master/app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

movies-master/app/views/libros/index.html.erb
<h1>Listing libros</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.name %></td>
        <td><%= link_to 'Show', libro %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path %>

movies-master/app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>

movies-master/app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @libro.name %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>

movies-master/app/views/movies/_form.html.erb
<% if @movie.errors.any? %>

	<% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
<% end %>

<form action="/movies<%= @movie.id ? '/'+@movie.id.to_s : '' %>" method="post">
	
	Nombre pelicula:
	<input type="text" name="movie[name]" value="<%= @movie.name %>">
	<br>
	<input type="submit" name="commit" value="Guardar">
</form>

movies-master/app/views/movies/create.html.erb
<b>Pelicula creada exitosamente!</b>
<a href="/">atras</a>

movies-master/app/views/movies/edit.html.erb
<h1>Editar pelicula</h1>
<%= render 'form' %>

movies-master/app/views/movies/index.html.erb
<b>Peliculas</b>
<br>
Cantidad de peliculas: <%= @movies.count %>

<br>
<%= notice %>
<table>
	<tr>
	<th>Pelicula</th>
	<th></th>
	</tr>

<% @movies.each do |movie| %>
	<tr>
	<td>
	<%= movie.name %>
	</td>
	<td>
		<a href="/movies/<%= movie.id %>">Editar</a>
	</td>
	</tr>

<% end %>

</table>

<br>
<a href="/movies/new">Nuevo</a>

movies-master/app/views/movies/new.html.erb
<b>Nueva Pelicula</b>
<%= render 'form' %>

movies-master/app/views/movies/nuevo.html.erb
hola mundo